name: Continuous Integration

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:

jobs:
  go-ci:
    strategy:
      matrix:
        make_action: ["build", "lint"]
    runs-on: ubuntu-latest
    name: "${{matrix.make_action}} planetarium"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: "${{matrix.make_action}} Code"
        run: make ${{matrix.make_action}}
